OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := pitch_mod.sfc
ROM_NAME := PITCH MOD
USE_LIB  := 1
LIB_MODULES := console apu

CSRC   := main.c
ASMSRC := data.asm
SPCSRC := player.spc700.asm

include $(OPENSNES)/make/common.mk
