OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := hires_text.sfc
ROM_NAME := HIRES TEXT

USE_LIB  := 1
LIB_MODULES := console dma background

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
