OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := hdma_wave_table.sfc
ROM_NAME := HDMA WAVE TABLE

USE_LIB  := 1
LIB_MODULES := console dma background hdma

CSRC := main.c

include $(OPENSNES)/make/common.mk
