OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := direct_color.sfc
ROM_NAME := DIRECT COLOR
USE_LIB  := 1
LIB_MODULES := console dma background colormath input

CSRC := main.c

include $(OPENSNES)/make/common.mk
