OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := hicolor_blend.sfc
ROM_NAME := HICOLOR BLEND

USE_LIB  := 1
LIB_MODULES := console dma background colormath

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
