OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := soundboard.sfc
ROM_NAME := SOUNDBOARD
USE_LIB  := 1
LIB_MODULES := console audio input

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
