OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := hdma_indirect_gradient.sfc
ROM_NAME := HDMA INDIRECT GRAD

USE_LIB  := 1
LIB_MODULES := console dma hdma

CSRC := main.c

include $(OPENSNES)/make/common.mk
