OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := gradient_9bit.sfc
ROM_NAME := GRADIENT 9BIT

USE_LIB  := 1
LIB_MODULES := console dma hdma

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
