OPENSNES := $(shell cd ../.. && pwd)

TARGET   := libtest.sfc
ROM_NAME := LIB RUNTIME TEST

USE_LIB  := 1
LIB_MODULES := console sprite dma background text math

CSRC := main.c

include $(OPENSNES)/make/common.mk
