OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := shadow_tint.sfc
ROM_NAME := SHADOW AND TINT
USE_LIB  := 1
LIB_MODULES := console dma background colormath input

CSRC := main.c

include $(OPENSNES)/make/common.mk
