OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := play_noise.sfc
ROM_NAME := PLAY NOISE
USE_LIB  := 1
LIB_MODULES := console apu

CSRC   := main.c
ASMSRC := data.asm
SPCSRC := player.spc700.asm

include $(OPENSNES)/make/common.mk
