OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := palette_cycle.sfc
ROM_NAME := PALETTE CYCLE
USE_LIB  := 1
LIB_MODULES := console dma background input

CSRC := main.c

include $(OPENSNES)/make/common.mk
